/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorldsRouteImport } from './routes/worlds'
import { Route as MissionRouteImport } from './routes/mission'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as InitiativesRouteImport } from './routes/initiatives'
import { Route as EventsRouteImport } from './routes/events'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AchievementsRouteImport } from './routes/achievements'
import { Route as IndexRouteImport } from './routes/index'

const WorldsRoute = WorldsRouteImport.update({
  id: '/worlds',
  path: '/worlds',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionRoute = MissionRouteImport.update({
  id: '/mission',
  path: '/mission',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const InitiativesRoute = InitiativesRouteImport.update({
  id: '/initiatives',
  path: '/initiatives',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AchievementsRoute = AchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/initiatives': typeof InitiativesRoute
  '/library': typeof LibraryRoute
  '/mission': typeof MissionRoute
  '/worlds': typeof WorldsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/initiatives': typeof InitiativesRoute
  '/library': typeof LibraryRoute
  '/mission': typeof MissionRoute
  '/worlds': typeof WorldsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/initiatives': typeof InitiativesRoute
  '/library': typeof LibraryRoute
  '/mission': typeof MissionRoute
  '/worlds': typeof WorldsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/achievements'
    | '/community'
    | '/contact'
    | '/events'
    | '/initiatives'
    | '/library'
    | '/mission'
    | '/worlds'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/achievements'
    | '/community'
    | '/contact'
    | '/events'
    | '/initiatives'
    | '/library'
    | '/mission'
    | '/worlds'
  id:
    | '__root__'
    | '/'
    | '/achievements'
    | '/community'
    | '/contact'
    | '/events'
    | '/initiatives'
    | '/library'
    | '/mission'
    | '/worlds'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AchievementsRoute: typeof AchievementsRoute
  CommunityRoute: typeof CommunityRoute
  ContactRoute: typeof ContactRoute
  EventsRoute: typeof EventsRoute
  InitiativesRoute: typeof InitiativesRoute
  LibraryRoute: typeof LibraryRoute
  MissionRoute: typeof MissionRoute
  WorldsRoute: typeof WorldsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/worlds': {
      id: '/worlds'
      path: '/worlds'
      fullPath: '/worlds'
      preLoaderRoute: typeof WorldsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mission': {
      id: '/mission'
      path: '/mission'
      fullPath: '/mission'
      preLoaderRoute: typeof MissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/initiatives': {
      id: '/initiatives'
      path: '/initiatives'
      fullPath: '/initiatives'
      preLoaderRoute: typeof InitiativesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achievements': {
      id: '/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AchievementsRoute: AchievementsRoute,
  CommunityRoute: CommunityRoute,
  ContactRoute: ContactRoute,
  EventsRoute: EventsRoute,
  InitiativesRoute: InitiativesRoute,
  LibraryRoute: LibraryRoute,
  MissionRoute: MissionRoute,
  WorldsRoute: WorldsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
